name: yourself_in_time_project
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.19.5 <3.0.0'


dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.2
  
  get: ^4.6.5
  intl:
  liquid_swipe: ^3.0.1
  smooth_page_indicator: ^1.0.0+2
  flutter_datetime_picker: ^1.5.1
  get_storage:
  flutter_native_timezone: 
  rxdart: ^0.27.6
  responsive_builder: ^0.4.3
  flutter_local_notifications: ^9.6.0
  lottie: ^1.4.2
  date_picker_timeline:
  sqflite:
  flutter_staggered_animations:
  image_picker: ^0.8.3
  font_awesome_flutter: ^10.2.1
  flutter_shapes: ^0.3.0
  provider: ^6.0.4
  flutter_feather_icons: ^2.0.0+1
  tcard: ^1.3.5
  fl_chart: ^0.55.2
  flutter_slidable: ^2.0.0
  table_calendar: ^3.0.8
  glassmorphism: ^3.0.0
  flutter_calendar_carousel: ^2.4.2
  #SNACKBAR
  animated_snack_bar: ^0.3.1
  #DI
  get_it: ^7.6.0

  #UTILS
  freezed: ^2.3.4

  #STATE_MANAGEMENT
  stacked: 
  stacked_services: 

  #FIREBASE
  firebase_core: ^2.12.0
  firebase_auth: ^4.6.0
  cloud_firestore: ^4.8.1
  

  #SIGN
  google_sign_in: ^6.1.4
  #UI
  animations: ^2.0.1
  google_fonts: ^3.0.1
  connectivity_plus: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: 
  stacked_generator: 
  flutter_launcher_icons: ^0.13.1
  
flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/timeecatch.png"  

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
     - assets/images/
     - assets/json/
  #   - images/a_dot_ham.jpeg



  